model = "gpt-5.1-codex"
model_reasoning_effort = "medium"

[projects."/home/duong/work/go/src/github.com/ms-practice"]
trust_level = "trusted"

[projects."/media/duong/01D852B60096ADB0/en"]
trust_level = "trusted"

[projects."/media/duong/01D852B60096ADB0/en/generate voice"]
trust_level = "trusted"
