model = "gpt-5.2-codex"
model_reasoning_effort = "medium"

[projects."/Users/exe-macbook/duong/go/src/github.com/OwnExcercise/ms-practice"]
trust_level = "trusted"

[projects."/Users/exe-macbook/duong/go/src/github.com/OwnExcercise"]
trust_level = "trusted"

[projects."/Users/exe-macbook/duong/go/src/github.com/lh-starlink"]
trust_level = "trusted"

[projects."/Users/exe-macbook/duong/ops/aws/light-house"]
trust_level = "trusted"

[projects."/Users/exe-macbook/duong/ops/aws/te-sso-infra"]
trust_level = "trusted"

[projects."/Users/exe-macbook/duong/go/src/github.com/k8s/k8s_config"]
trust_level = "trusted"

[projects."/Users/exe-macbook/duong/go/src/github.com/OwnExcercise/kafka-beginners-course"]
trust_level = "trusted"

[projects."/Users/exe-macbook/duong/dotfiles/dotfiles"]
trust_level = "trusted"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex" = "gpt-5.2-codex"

[sandbox_workspace_write]
network_access = true

[sandbox_workspace_write.allowlist]
domains = [
"alpinelinux.org",
"anaconda.com",
"apache.org",
"apt.llvm.org",
"archlinux.org",
"azure.com",
"bitbucket.org",
"bower.io",
"centos.org",
"cocoapods.org",
"continuum.io",
"cpan.org",
"crates.io",
"debian.org",
"docker.com",
"docker.io",
"dot.net",
"dotnet.microsoft.com",
"eclipse.org",
"fedoraproject.org",
"gcr.io",
"ghcr.io",
"github.com",
"githubusercontent.com",
"gitlab.com",
"golang.org",
"google.com",
"goproxy.io",
"gradle.org",
"hashicorp.com",
"haskell.org",
"hex.pm",
"java.com",
"java.net",
"jcenter.bintray.com",
"json-schema.org",
"json.schemastore.org",
"k8s.io",
"launchpad.net",
"maven.org",
"mcr.microsoft.com",
"metacpan.org",
"microsoft.com",
"nodejs.org",
"npmjs.com",
"npmjs.org",
"nuget.org",
"oracle.com",
"packagecloud.io",
"packages.microsoft.com",
"packagist.org",
"pkg.go.dev",
"ppa.launchpad.net",
"pub.dev",
"pypa.io",
"pypi.org",
"pypi.python.org",
"pythonhosted.org",
"quay.io",
"ruby-lang.org",
"rubyforge.org",
"rubygems.org",
"rubyonrails.org",
"rustup.rs",
"rvm.io",
"sourceforge.net",
"spring.io",
"swift.org",
"ubuntu.com",
"visualstudio.com",
"yarnpkg.com"
]

[features]
web_search_request = true

